### ISSUE TITLE
Color-Flags are not saved

### ISSUE THREAD

**Issue by Luki2410** [Mark-225/BlueBridge#10]
After setting any of the color flags 'bluemap-color' or 'bluemap-color-outline' there is nothing changing on the map itself.
I can set the color directly in the marker file but after changing any other flag like 'bluemap-render-height' for example, the color is set back again to the default value and not to the value defined in the region flag. The value in the region flag itself is never overriden by the way, so it appears that its just not setting the values in the marker file.

Using the latest version of all involved plugins:

BlueBridge (v1.3.1-alpha)
BlueMap (1.5.5)
WorldGuard (7.0.5)
Paper 1.16.5 (Build #779)

**Comment by Mark-225** [comment]
Hmm, I did specifically test custom color flags and they worked on my test server... I will investigate this and if I find something, a fix will be included in the next release (I won't release this fix on its own like your previous issues, because it seems pretty minor and I don't want to annoy Spigot users with a new update notification every day :D)

**Comment by Mark-225** [comment]
Okay after booting up my testserver real quick it still works without any issues for me, but I have an idea why it might not work for you:  
The worldguard flags have to be hexadecimal numbers that match these formats:
 - "AARRGGBB" for bluemap-color.
 - "RRGGBB" for bluemap-color-outline
 (AA would be the alpha channel)
   
Note that there is no "#" in front like you would put it in html tags. So if you want a red outline with a transparent blue fill color you would use:
 - bluemap-color-outline = "ff0000"
 - bluemap-color = "960000ff"
   
It's also case-sensitive and expects lower case characters. so "FF0000" for red would default back to the color set in the config.
If you're not sure, you can send me exactly what you tried to set your flags to, so I can take a look at it and see if something's wrong.

**Comment by Luki2410** [comment]
Ahh thanks a lot, it was because of case sensitive.
Had no idea it must be lower case, because some plugins I use are using upper case letters.
Thanks :D

**Comment by Mark-225** [comment]
Yeah I will probably make it accept both upper- and lowercase in the next update. It's a simple change and will avoid a lot of confusion in the future. Glad you got it working and thanks for all your feedback!
