### ISSUE TITLE
[Bug] Can't overwrite min/max distances

### ISSUE THREAD

**Issue by Happy-Hop7** [Mark-225/BlueBridge#11]
From the wiki:
<html><body>

Name | Datatype | Description | Default | Can be overwritten?
-- | -- | -- | -- | --
minDistancemaxDistance | Integer | When set to any value greater than 0, determines the min/max distance of the camera to the region for it to be visible. | -1-1 |  **Yes**

</body>
</html>

Every time I change "minDistance" and "maxDistance" values in my bluemap markers.json, it get's reset to the values in my BlueBridge Core config.yml

Is this a bug or is there an other way to overwrite this values for a specific region?

Server Version: purpur 1.18.1 #1502
Bluemap Version: 1.7.2
BlueBridgeCore Version: 1.3.1
BlueBridgeWG Version: 1.3.1

**Comment by Mark-225** [comment]
Not strictly a bug, but an oversight on my part. The config setting definitely should have had a WorldGuard flag from the beginning.

I fixed it by adding "bluemap-min-distance" and "bluemap-max-distance" as individually configurable WorldGuard flags.
You can download the dev build here if you don't want to wait for the proper release after I tested it:
https://github.com/Mark-225/BlueBridge/actions/runs/1689199171

(Leaving this issue open until the release so other people who might have the same issue can find it easier)

**Comment by Mark-225** [comment]
Should be fixed in release 2.1
