### ISSUE TITLE
Does this work with blue-cli?

### ISSUE THREAD

**Issue by cunhar** [Mark-225/BlueBridge#25]

**Comment by Mark-225** [comment]
No it does not for two reasons:
1. I use the plugin's api's to get region/claim data. These plugins are only available on a spigot/paper server. Theoretically, I could also load the data from whereever the plugins save it, but the file format or database structure might break with updates, making this approach less maintainable than using an API.
2. Bluemap CLI cannot load addons on it's own. It needs to run on a platform that allows loading mods or plugins for addons to work.

That means live updating markers will most likely never exist for Bluemap CLI. What I thought of doing was adding a command to export a "snapshot" of the areas on a server to a json string that can be used in a map config on Bluemap CLI. But I don't know if that would be useful for you.
