### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by jurohn** [Mark-225/BlueBridge#29]
Do you have plans to update this plugin to 1.21?

Edit 12/08/24: 1.21.1

**Comment by jurohn** [comment]
20.07 18:32:41 [Server] WARN [BlueBridgeGP] "BlueBridgeGP v2.1" has registered a listener for me.ryanhamshire.GriefPrevention.events.ClaimModifiedEvent on method "public void de.mark225.bluebridge.griefprevention.addon.listener.GriefPreventionListener.onClaimModified(me.ryanhamshire.GriefPrevention.events.ClaimModifiedEvent)", but the event is Deprecated. "ClaimModifiedEvent will be removed in favor of ClaimResizeEvent"; please notify the authors [Mark_225, Aurelien30000].

@Mark-225

**Comment by Mark-225** [comment]
Update is released. I have tested every component but not too thoroughly, so let me know if you find any issues.
