### ISSUE TITLE
Outdated ?!? Missing link of blueguard in the description.

### ISSUE THREAD

**Issue by ErythroCraft** [Mark-225/BlueBridge#6]
Hi.

I've seen your plugin is outdated and switching to blueguard.

Can you fix the description on spigot and type an link for blueguard, please?

Thanks

**Comment by ErythroCraft** [comment]
Maybe an link of BlueBridgeCore and BlueBridgeWG, too.

**Comment by Mark-225** [comment]
Actually, BlueGuard is the outdated plugin. I made that one first as a standalone BlueMap-WorldGuard bridge but then wanted to start adding support for more region plugins (like GriefPrevention) so I rewrote BlueGuard into BlueBridgeCore and BlueBridgeWG.    
Both the Spigot resource page and the old BlueGuard repo should state that BlueGuard is outdated and users of that should switch to BlueBridge for future updates. Is there any descriptions or something I forgot to update or where did you get this information from?
