### ISSUE TITLE
Marker file gets flushed after reload

### ISSUE THREAD

**Issue by Luki2410** [Mark-225/BlueBridge#8]
I found another bug and thought it would be better to open up a new issue.

If you do a reload of BlueMap, the marker file is newly generated and it's empty then.
After a server restart it retrieves the data from worldguard and fills the marker file again with information, at least for the overworld.

My currently used workaround is to copy the content of the marker file before reloading and filling it again afterwards. Then a refresh of the browser is enough to bring back the markings on BlueMap.

Using the latest version of all involved plugins:

BlueBridge (v1.3-alpha)
BlueMap (1.5.5)
WorldGuard (7.0.5)
Paper 1.16.5 (Build #779)

**Comment by Mark-225** [comment]
Just commenting here to clarify that this is also fixed in v1.3.1-alpha, which was just released. The regions may disappear for a short time directly after a BlueMap reload but that is intended. They should now automatically reappear after a maximum of about 20 seconds.
